name: json_on_map
description: json data on map

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  file_picker: ^5.1.0
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/example1.png
    - assets/images/example2.png
